// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhaoyuxing/Desktop/blog/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/zhaoyuxing/Desktop/blog/node_modules/dumi/theme-default/slots/SearchBar/index.js';
